/* Extracted verbatim from the reference site's privacy.dc.html — its own
   sectionData() array, evaluated rather than re-typed, so every clause, every
   curly quote and every definition matches the source exactly.

   Ten sections, fifty-two blocks. The clauses are the source's own — nothing is
   paraphrased, because it is a legal notice and rewording it changes what the
   business has committed to. What has been changed is copy-editing only:
   typos, agreement, missing articles and punctuation the source got wrong, plus
   the You/Your capitalisation the document itself sets up and then drops in a
   few places. Meaning is untouched. */

export type PolicyBlock =
  | { t: 'p'; text: string }
  | { t: 'h'; text: string }
  | { t: 'ul'; items: string[] }
  /* A clause the source set in full capitals — warranty disclaimers, liability
     limits, the acknowledgement. Caps are the legal convention for making a
     clause conspicuous; a wall of them is also close to unreadable. These carry
     the same text in sentence case and are made conspicuous by design instead. */
  | { t: 'note'; text: string };

export type PolicySection = {
  title: string;
  blocks: PolicyBlock[];
};

export const policyUpdated = 'Last updated: 4 July 2022';

export const policySections: PolicySection[] = [
  {
    "title": "Interpretation and Definitions",
    "blocks": [
      {
        "t": "p",
        "text": "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You."
      },
      {
        "t": "p",
        "text": "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy."
      },
      {
        "t": "h",
        "text": "Interpretation"
      },
      {
        "t": "p",
        "text": "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
      },
      {
        "t": "h",
        "text": "Definitions"
      },
      {
        "t": "p",
        "text": "For the purposes of this Privacy Policy:"
      },
      {
        "t": "ul",
        "items": [
          "Account means a unique account created for You to access our Service or parts of our Service.",
          "Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Deep Real Estate, G-564, Sushant Lok-II Extn., Sector 57, Nr. Scottish High Gurgaon, Haryana-122002, India.",
          "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
          "Country refers to Haryana, India.",
          "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
          "Personal Data is any information that relates to an identified or identifiable individual.",
          "Service refers to the Website.",
          "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
          "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
          "Website refers to Deep Real Estate, accessible from http://www.deeprealestate.in.",
          "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
        ]
      }
    ]
  },
  {
    "title": "Types of Data Collected",
    "blocks": [
      {
        "t": "h",
        "text": "Personal Data"
      },
      {
        "t": "p",
        "text": "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:"
      },
      {
        "t": "ul",
        "items": [
          "Email address",
          "First name and last name",
          "Phone number",
          "Address, State, Province, ZIP/Postal code, City",
          "Usage Data"
        ]
      },
      {
        "t": "h",
        "text": "Usage Data"
      },
      {
        "t": "p",
        "text": "Usage Data is collected automatically when using the Service."
      },
      {
        "t": "p",
        "text": "Usage Data may include information such as Your Device’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."
      },
      {
        "t": "p",
        "text": "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data."
      },
      {
        "t": "p",
        "text": "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device."
      }
    ]
  },
  {
    "title": "Tracking Technologies and Cookies",
    "blocks": [
      {
        "t": "p",
        "text": "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:"
      },
      {
        "t": "ul",
        "items": [
          "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless You have adjusted Your browser settings so that they will refuse Cookies, our Service may use Cookies.",
          "Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.",
          "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics."
        ]
      },
      {
        "t": "p",
        "text": "Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser."
      },
      {
        "t": "p",
        "text": "We use both Session and Persistent Cookies for the purposes set out below:"
      },
      {
        "t": "ul",
        "items": [
          "Necessary/Essential Cookies (Session Cookies, administered by Us): These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.",
          "Cookies Policy/Notice Acceptance Cookies (Persistent Cookies, administered by Us): These Cookies identify if users have accepted the use of cookies on the Website.",
          "Functionality Cookies (Persistent Cookies, administered by Us): These Cookies allow us to remember choices You make when You use the Website, such as remembering Your login details or language preference."
        ]
      },
      {
        "t": "p",
        "text": "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy."
      }
    ]
  },
  {
    "title": "Use of Your Personal Data",
    "blocks": [
      {
        "t": "p",
        "text": "The Company may use Personal Data for the following purposes:"
      },
      {
        "t": "ul",
        "items": [
          "To provide and maintain our Service, including to monitor the usage of our Service.",
          "To manage Your Account: To manage Your registration as a user of the Service.",
          "For the performance of a contract: The development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
          "To contact You: To contact You by email, telephone calls, SMS or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services, including security updates, when necessary or reasonable.",
          "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that You have already purchased or enquired about, unless You have opted not to receive such information.",
          "To manage Your requests: To attend to and manage Your requests to Us.",
          "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of Our assets.",
          "For other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."
        ]
      }
    ]
  },
  {
    "title": "Sharing Your Personal Data",
    "blocks": [
      {
        "t": "p",
        "text": "We may share Your personal information in the following situations:"
      },
      {
        "t": "ul",
        "items": [
          "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, or to contact You.",
          "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
          "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.",
          "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.",
          "With other users: When You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
          "With Your consent: We may disclose Your personal information for any other purpose with Your consent."
        ]
      }
    ]
  },
  {
    "title": "Retention & Transfer of Your Personal Data",
    "blocks": [
      {
        "t": "h",
        "text": "Retention of Your Personal Data"
      },
      {
        "t": "p",
        "text": "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes and enforce our legal agreements and policies."
      },
      {
        "t": "p",
        "text": "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."
      },
      {
        "t": "h",
        "text": "Transfer of Your Personal Data"
      },
      {
        "t": "p",
        "text": "Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction."
      },
      {
        "t": "p",
        "text": "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer."
      },
      {
        "t": "p",
        "text": "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information."
      }
    ]
  },
  {
    "title": "Disclosure of Your Personal Data",
    "blocks": [
      {
        "t": "h",
        "text": "Business Transactions"
      },
      {
        "t": "p",
        "text": "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy."
      },
      {
        "t": "h",
        "text": "Law enforcement"
      },
      {
        "t": "p",
        "text": "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency)."
      },
      {
        "t": "h",
        "text": "Other legal requirements"
      },
      {
        "t": "p",
        "text": "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:"
      },
      {
        "t": "ul",
        "items": [
          "Comply with a legal obligation",
          "Protect and defend the rights or property of the Company",
          "Prevent or investigate possible wrongdoing in connection with the Service",
          "Protect the personal safety of Users of the Service or the public",
          "Protect against legal liability"
        ]
      }
    ]
  },
  {
    "title": "Security of Your Personal Data",
    "blocks": [
      {
        "t": "p",
        "text": "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
      }
    ]
  },
  {
    "title": "Children’s Privacy & Links to Other Websites",
    "blocks": [
      {
        "t": "h",
        "text": "Children’s Privacy"
      },
      {
        "t": "p",
        "text": "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."
      },
      {
        "t": "p",
        "text": "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information."
      },
      {
        "t": "h",
        "text": "Links to Other Websites"
      },
      {
        "t": "p",
        "text": "Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit."
      },
      {
        "t": "p",
        "text": "We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services."
      }
    ]
  },
  {
    "title": "Changes & Contact Us",
    "blocks": [
      {
        "t": "h",
        "text": "Changes to this Privacy Policy"
      },
      {
        "t": "p",
        "text": "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page."
      },
      {
        "t": "p",
        "text": "We will let You know via email and/or a prominent notice on Our Service prior to the change becoming effective, and update the “Last updated” date at the top of this Privacy Policy."
      },
      {
        "t": "p",
        "text": "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
      },
      {
        "t": "h",
        "text": "Contact Us"
      },
      {
        "t": "p",
        "text": "If You have any questions about this Privacy Policy, You can contact us by email at info@deeprealestate.in, by phone at +91-9810922338, or by mail at G-564, Sushant Lok-II Extn., Sector 57, Nr. Scottish High Gurgaon, Haryana-122002, India."
      }
    ]
  }
];
